# Generated by Django 4.1.6 on 2023-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField(default='0')),
                ('longitude', models.TextField(default='0')),
                ('date', models.DateField()),
                ('time', models.TimeField(default='0:0:0')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNum', models.TextField(default='')),
                ('color', models.TextField(default='')),
                ('model', models.TextField(default='')),
                ('brand', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField(default='0')),
                ('longitude', models.TextField(default='0')),
                ('contactNumber', models.TextField(default='0000000000')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField(default='0')),
                ('longitude', models.TextField(default='0')),
                ('contactNumber', models.TextField(default='0000000000')),
                ('branch', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('contactNumber', models.TextField(default='0000000000')),
                ('street', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('state', models.TextField(default='')),
            ],
        ),
    ]
