# Generated by Django 3.2.3 on 2023-02-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0002_accidentalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentalert',
            name='accId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amsApp.accident'),
        ),
        migrations.AddField(
            model_name='accidentalert',
            name='hosId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amsApp.hospital'),
        ),
        migrations.AddField(
            model_name='accidentalert',
            name='polId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amsApp.policestation'),
        ),
    ]
