# Generated by Django 3.2.3 on 2023-02-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0003_auto_20230212_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentVictims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsApp.accident')),
                ('vicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsApp.victim')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsApp.accident')),
                ('vehId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsApp.car')),
            ],
        ),
    ]
