# Generated by Django 3.2.3 on 2023-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0004_accidentvehicles_accidentvictims'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentalert',
            name='hosAttend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accidentalert',
            name='polAttend',
            field=models.BooleanField(default=False),
        ),
    ]
