# Generated by Django 3.2.3 on 2023-02-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0005_auto_20230214_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='owner',
            field=models.TextField(default=''),
        ),
    ]
