# Generated by Django 3.2.3 on 2023-02-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0006_victim_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='owner',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.TextField(default=''),
        ),
    ]
