# Generated by Django 3.2.3 on 2023-02-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0007_auto_20230214_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default='0', max_digits=20),
        ),
        migrations.AlterField(
            model_name='accident',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default='0', max_digits=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default='0', max_digits=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default='0', max_digits=20),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default='0', max_digits=20),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default='0', max_digits=20),
        ),
    ]
