# Generated by Django 3.2.3 on 2023-02-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0009_auto_20230224_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
